services:
  - type: web
    name: minha-app-flask
    env: docker
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: FLASK_ENV
        value: production